startuppopupversion: 1
gui:
  theme:
    activeBorderColor:
      - default
      - bold
    inactiveBorderColor:
      - default
    selectedLineBgColor:
      - green
keybinding:
  universal:
    togglePanel: '<tab>'
    prevBlock-alt: '<c-k>'
    nextBlock-alt: '<c-j>'
  commits:
    moveDownCommit: 'J' # move commit down one
    moveUpCommit: 'K' # move commit up one
os:
  openCommand: 'vim {{filename}}'
